spring:
  profiles:
    active: local

  main:
    web-application-type: none

  application:
    name: boogle

  data:
    elasticsearch:
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.orm.jdbc.bind: trace # 바인딩 파라미터 값 확인하고 싶을 때 켜기