spring:
  profiles:
    active: local

  main:
    web-application-type: none

  application:
    name: boogle

  data:
    elasticsearch:
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  batch:
    jdbc:
      initialize-schema: always # 배치가 실행될 때 필요한 메타 테이블들을 자동 생성해줌
    job:
      enabled: true # jenkins로 해당 잡을 실행하려면 enabled의 값이 true여야 함

logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.orm.jdbc.bind: trace # 바인딩 파라미터 값 확인하고 싶을 때 켜기